/**
 * Builds browser assets from shared TypeScript:
 *   web/engine.js          ← src/engine/engine.ts (types stripped)
 *   dist/firstprint-preview.html ← single-file demo (no server needed)
 */
import { stripTypeScriptTypes } from 'node:module';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (p: string) => readFileSync(new URL(p, root), 'utf8');

const engineTs = read('src/engine/engine.ts');
const engineJs =
  '// Generated by scripts/build-web.ts from src/engine/engine.ts. Do not edit.\n' +
  stripTypeScriptTypes(engineTs, { mode: 'strip' }).replace(/\n\s*\n\s*\n+/g, '\n\n');
writeFileSync(new URL('web/engine.js', root), engineJs);

/** Removes ES module syntax so files can share one inline <script>. */
const inline = (src: string) =>
  src
    .replace(/^import[\s\S]*?from\s+['"][^'"]+['"];?\s*$/gm, '')
    .replace(/^export\s+(?=(async\s+)?(function|class|const|let))/gm, '');

const html = read('web/index.html');
const css = read('web/styles.css');
const js = [engineJs, read('web/api.js'), read('web/wallet.js'), read('web/demo.js'), read('web/app.js')].map(inline).join('\n;\n');

const preview = html
  .replace(/<link rel="stylesheet" href="\.\/styles\.css"\s*\/?>/, () => `<style>\n${css}\n</style>`)
  .replace(/<script type="module" src="\.\/app\.js"><\/script>/, () => `<script>window.FP_FORCE_DEMO = true;</script>\n<script type="module">\n${js}\n</script>`);

mkdirSync(new URL('dist/', root), { recursive: true });
writeFileSync(new URL('dist/firstprint-preview.html', root), preview);
console.log(`web/engine.js ${engineJs.length} bytes, dist/firstprint-preview.html ${preview.length} bytes`);
