// Generated by scripts/build-web.ts from src/engine/engine.ts. Do not edit.
/**
 * Firstprint market engine.
 *
 * Pure, dependency-free logic shared by the server and the Mini App:
 * outcome buckets, TWAP price oracle, pool caps, early-bird weights,
 * payouts, and settlement with void rules.
 *
 * Amounts are integers in minor units (points, or USDT micro-units later).
 * Times are Unix milliseconds.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Ordered from worst to best outcome. */
export const BUCKETS                    = ['crash', 'down', 'flat', 'up', 'moon'];

export const DEFAULT_THRESHOLDS             = { crash: -0.5, down: -0.1, up: 0.1, moon: 0.5 };

const MINUTE = 60_000;
const HOUR = 60 * MINUTE;

export const DEFAULT_CONFIG               = {
  thresholds: DEFAULT_THRESHOLDS,
  earlyBirdK: 0.5,
  feeBps: 400,
  softCap: 50_000,
  volumeCapRatio: null,
  perUserCapPct: 0.1,
  baselineMs: HOUR,
  durationMs: 72 * HOUR,
  settleWindowMs: HOUR,
  minCoverage: 0.5,
  minTrades: 10,
  maxListingDelayMs: 24 * HOUR,
  maxHaltMs: 6 * HOUR,
};

// ---------------------------------------------------------------------------
// Buckets
// ---------------------------------------------------------------------------

/** Rounds away float noise so exactly -10% lands in "down", not "flat". */
function clean(r        )         {
  return Math.round(r * 1e9) / 1e9;
}

export function returnPct(base        , final        )         {
  if (!(base > 0) || !(final >= 0)) throw new Error('Prices must be positive');
  return clean(final / base - 1);
}

export function bucketForReturn(r        , t             = DEFAULT_THRESHOLDS)         {
  const x = clean(r);
  if (x <= t.crash) return 'crash';
  if (x <= t.down) return 'down';
  if (x < t.up) return 'flat';
  if (x < t.moon) return 'up';
  return 'moon';
}

export function bucketRangeLabel(b        , t             = DEFAULT_THRESHOLDS)         {
  const p = (n        ) => `${n > 0 ? '+' : ''}${Math.round(n * 100)}%`;
  switch (b) {
    case 'crash': return `${p(t.crash)} or worse`;
    case 'down': return `${p(t.crash)} to ${p(t.down)}`;
    case 'flat': return `${p(t.down)} to ${p(t.up)}`;
    case 'up': return `${p(t.up)} to ${p(t.moon)}`;
    case 'moon': return `${p(t.moon)} or better`;
  }
}

// ---------------------------------------------------------------------------
// Price oracle
// ---------------------------------------------------------------------------

/**
 * Time-weighted average of 1-minute closes over [start, end).
 * Missing minutes carry the last known price forward, including the last
 * candle before the window. Slots before any known price are skipped.
 */
export function twap(candles                   , start        , end        )              {
  const sorted = [...candles].sort((a, b) => a.ts - b.ts);
  const slots = Math.max(0, Math.floor((end - start) / MINUTE));
  if (slots === 0) return { twap: null, coverage: 0, volume: 0, trades: null };

  const byMinute = new Map                ();
  let last                = null;
  for (const c of sorted) {
    if (c.ts < start) last = c.close;
    else if (c.ts < end) byMinute.set(Math.floor((c.ts - start) / MINUTE), c);
  }

  let sum = 0;
  let priced = 0;
  let real = 0;
  let volume = 0;
  let trades = 0;
  let hasTrades = false;

  for (let i = 0; i < slots; i++) {
    const c = byMinute.get(i);
    if (c) {
      last = c.close;
      real++;
      volume += c.volume;
      if (c.trades !== undefined) {
        trades += c.trades;
        hasTrades = true;
      }
    }
    if (last !== null) {
      sum += last;
      priced++;
    }
  }

  return {
    twap: priced > 0 ? sum / priced : null,
    coverage: real / slots,
    volume,
    trades: hasTrades ? trades : null,
  };
}

/**
 * Volume-weighted median across venues. A single venue with little volume
 * can't drag the result far. Falls back to a plain median without volume.
 */
export function venueMedian(venues                       )                {
  const valid = venues.filter((v)                                      => v.price !== null && v.price > 0);
  if (valid.length === 0) return null;
  const sorted = [...valid].sort((a, b) => a.price - b.price);
  const total = sorted.reduce((s, v) => s + Math.max(0, v.volume), 0);

  if (total <= 0) {
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[mid].price : (sorted[mid - 1].price + sorted[mid].price) / 2;
  }

  let cum = 0;
  for (const v of sorted) {
    cum += Math.max(0, v.volume);
    if (cum >= total / 2) return v.price;
  }
  return sorted[sorted.length - 1].price;
}

// ---------------------------------------------------------------------------
// Pool
// ---------------------------------------------------------------------------

export function weightFor(placedAt        , tOpen        , tClose        , k        )         {
  if (tClose <= tOpen) return 1;
  const f = (tClose - placedAt) / (tClose - tOpen);
  return 1 + k * Math.min(1, Math.max(0, f));
}

export function hardCapFor(cfg              , baselineVolume        )         {
  if (cfg.volumeCapRatio === null) return cfg.softCap;
  return Math.max(0, Math.min(cfg.softCap, Math.floor(cfg.volumeCapRatio * baselineVolume)));
}

/**
 * Applies the pool hard cap and per-user cap in time order, so the latest
 * predictions are the ones refunded when a cap is hit.
 */
export function applyCaps(
  predictions                       ,
  hardCap        ,
  cfg                                                    ,
  tOpen        ,
  tClose        ,
)                       {
  const userCap = Math.floor(hardCap * cfg.perUserCapPct);
  const used = new Map                ();
  let poolLeft = hardCap;

  const ordered = [...predictions].sort((a, b) => a.placedAt - b.placedAt || a.id.localeCompare(b.id));
  return ordered.map((p) => {
    const userLeft = userCap - (used.get(p.userId) ?? 0);
    const accepted = Math.max(0, Math.min(p.stake, userLeft, poolLeft));
    used.set(p.userId, (used.get(p.userId) ?? 0) + accepted);
    poolLeft -= accepted;
    return {
      ...p,
      accepted,
      refund: p.stake - accepted,
      weight: weightFor(p.placedAt, tOpen, tClose, cfg.earlyBirdK),
    };
  });
}

export function emptyTotals()             {
  return { crash: 0, down: 0, flat: 0, up: 0, moon: 0 };
}

export function poolTotals(predictions                                              )             {
  const t = emptyTotals();
  for (const p of predictions) t[p.bucket] += p.stake;
  return t;
}

/** Estimated payout for a new prediction, assuming the pool doesn't change. */
export function quote(
  existing                       ,
  bucket        ,
  stake        ,
  placedAt        ,
  cfg                                             ,
  tOpen        ,
  tClose        ,
)        {
  const weight = weightFor(placedAt, tOpen, tClose, cfg.earlyBirdK);
  if (stake <= 0) return { weight, payout: 0, multiple: 0 };
  const pool = existing.reduce((s, p) => s + p.stake, 0) + stake;
  const net = pool - Math.floor((pool * cfg.feeBps) / 10_000);
  const winnersWeighted =
    existing
      .filter((p) => p.bucket === bucket)
      .reduce((s, p) => s + p.stake * weightFor(p.placedAt, tOpen, tClose, cfg.earlyBirdK), 0) +
    stake * weight;
  const payout = Math.floor((net * stake * weight) / winnersWeighted);
  return { weight, payout, multiple: payout / stake };
}

export function refundAll(accepted                               , reason            )             {
  return {
    pool: accepted.reduce((s, p) => s + p.accepted, 0),
    fee: 0,
    netPool: 0,
    dust: 0,
    voidReason: reason,
    payouts: accepted.map((p) => ({
      predictionId: p.id,
      userId: p.userId,
      bucket: p.bucket,
      accepted: p.accepted,
      refund: p.refund + p.accepted,
      payout: 0,
      weight: p.weight,
    })),
  };
}

export function computePayouts(
  accepted                               ,
  winning        ,
  cfg                              ,
)             {
  const live = accepted.filter((p) => p.accepted > 0);
  const pool = live.reduce((s, p) => s + p.accepted, 0);
  if (pool === 0) return refundAll(accepted, 'empty_pool');

  const bucketsUsed = new Set(live.map((p) => p.bucket));
  if (bucketsUsed.size < 2) return refundAll(accepted, 'one_sided_pool');

  const winners = live.filter((p) => p.bucket === winning);
  if (winners.length === 0) return refundAll(accepted, 'no_winners');

  const fee = Math.floor((pool * cfg.feeBps) / 10_000);
  const netPool = pool - fee;
  const totalWeighted = winners.reduce((s, p) => s + p.accepted * p.weight, 0);

  let paid = 0;
  const payouts           = accepted.map((p) => {
    const won = p.accepted > 0 && p.bucket === winning;
    const payout = won ? Math.floor((netPool * p.accepted * p.weight) / totalWeighted) : 0;
    paid += payout;
    return {
      predictionId: p.id,
      userId: p.userId,
      bucket: p.bucket,
      accepted: p.accepted,
      refund: p.refund,
      payout,
      weight: p.weight,
    };
  });

  return { pool, fee, netPool, dust: netPool - paid, payouts, voidReason: null };
}

// ---------------------------------------------------------------------------
// Settlement
// ---------------------------------------------------------------------------

export function windows(cfg              , listingAt        ) {
  const settleAt = listingAt + cfg.durationMs;
  return {
    baseline: { start: listingAt, end: listingAt + cfg.baselineMs },
    final: { start: settleAt - cfg.settleWindowMs, end: settleAt },
    closeAt: listingAt + cfg.baselineMs,
    settleAt,
  };
}

function windowOk(stats               , cfg              )          {
  const good = stats.filter((s) => s.twap !== null && s.coverage >= cfg.minCoverage);
  if (good.length === 0) return false;
  const reported = good.filter((s) => s.trades !== null);
  if (reported.length === 0) return true;
  return reported.reduce((n, s) => n + (s.trades ?? 0), 0) >= cfg.minTrades;
}

export function settleMarket(input                 )                   {
  const { cfg } = input;
  const w = windows(cfg, input.listingAt);
  const venues = Object.keys(input.candles);

  const baseStats                = venues.map((v) => ({ venue: v, ...twap(input.candles[v], w.baseline.start, w.baseline.end) }));
  const finalStats                = venues.map((v) => ({ venue: v, ...twap(input.candles[v], w.final.start, w.final.end) }));

  const pick = (stats               ) =>
    venueMedian(stats.filter((s) => s.coverage >= cfg.minCoverage).map((s) => ({ venue: s.venue, price: s.twap, volume: s.volume })));

  const basePrice = pick(baseStats);
  const finalPrice = pick(finalStats);

  const shell = {
    baseline: { ...w.baseline, price: basePrice, venues: baseStats },
    final: { ...w.final, price: finalPrice, venues: finalStats },
  };

  const voided = (reason            )                   => ({
    ...refundAll(input.accepted, reason),
    ...shell,
    returnPct: null,
    winningBucket: null,
  });

  if (input.retracted) return voided('retracted');
  if (input.listingAt - input.announcedListingAt > cfg.maxListingDelayMs) return voided('listing_delayed');
  if (input.haltedMs > cfg.maxHaltMs) return voided('trading_halted');
  if (basePrice === null || !windowOk(baseStats, cfg)) return voided('insufficient_baseline_data');
  if (finalPrice === null || !windowOk(finalStats, cfg)) return voided('insufficient_settlement_data');

  const r = returnPct(basePrice, finalPrice);
  const winning = bucketForReturn(r, cfg.thresholds);
  const pool = computePayouts(input.accepted, winning, cfg);

  return {
    ...pool,
    ...shell,
    // The measured outcome stays visible even if the pool itself is refunded.
    returnPct: r,
    winningBucket: winning,
  };
}
